name: "sotoganaderia"

networks:
  proxy:
    external: true
  ganaderia-internal-net:
    driver: bridge

services:
  sotoganaderia-db:
    image: postgres:15-alpine
    container_name: sotoganaderia-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ganaderia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ganaderia-internal-net
    ports:
      - "5441:5432"

  sotoganaderia-web:
    build: ./apps/web
    container_name: sotoganaderia-web
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-postgres}@sotoganaderia-db:5432/ganaderia?schema=public
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://ganaderia.sotodelprior.com}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_TRUST_HOST=true
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - NEXTAUTH_SKIP_ENV_VALIDATION=true
      - NODE_ENV=production
    env_file: .env
    networks:
      - proxy
      - ganaderia-internal-net
    depends_on:
      - sotoganaderia-db
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      # Router HTTP
      - "traefik.http.routers.sotoganaderia-web-http.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.sotoganaderia-web-http.entrypoints=web"
      - "traefik.http.routers.sotoganaderia-web-http.middlewares=redirect-to-https"
      # Router HTTPS
      - "traefik.http.routers.sotoganaderia-web.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.sotoganaderia-web.entrypoints=websecure"
      - "traefik.http.routers.sotoganaderia-web.tls=true"
      - "traefik.http.routers.sotoganaderia-web.tls.certresolver=le"
      # Servicio
      - "traefik.http.services.sotoganaderia-web.loadbalancer.server.port=3000"
      # Middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

volumes:
  postgres_data:
